--layout=reverse
--border=rounded
--prompt=" 󰍉 "
--pointer="→"
--color=bg+:#2d333b,bg:#22272e,spinner:#56d4dd,hl:#f47067
--color=fg:#adbac7,header:#768390,info:#b083f0,pointer:#539bf5
--color=marker:#57ab5a,fg+:#cdd9e5,prompt:#539bf5,hl+:#f47067
--color=border:#444c56
--preview="bat --style=numbers --color=always --line-range :500 {} 2>/dev/null || tree -C {}"
--preview-window="right:55%:border-rounded"
